# DisableCommand Plugin Configuration
# Cấu hình plugin DisableCommand

# Danh sách các command bị disable
disabled-commands:
  - "?"
  - "help" 
  - "pl"
  - "plugin"
  - "plugins"

# Thông báo khi người chơi sử dụng command bị disable
disabled-message: "&cCommand này đã bị disable!"

# Thông báo khi không có quyền
no-permission-message: "&cBạn không có quyền sử dụng command này!"

# Bật/tắt debug mode
debug: false